version: '3.8'

networks:
  app-network:
    driver: bridge
    external: true

services:
  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  app:
    image: "${APP_IMAGE:-rohittru/microservicecicdtest_${APP_NAME}:latest}"
    container_name: "${APP_NAME:-default-app}"
    ports:
      - "${APP_PORT:-5004}:${APP_PORT:-5004}"
    environment:
      - SERVICE_NAME=${APP_NAME:-default-app}
    depends_on:
      - redis
    networks:
      - app-network
