version: '3.8'

# Define custom Docker network
networks:
  app-network:
    driver: bridge

services:
  # Redis service
  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  # App1 service
  app1:
    build:
      context: ./app1
    container_name: app1
    ports:
      - "5004:5004"
    depends_on:
      - redis
    networks:
      - app-network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  # App2 service
  app2:
    build:
      context: ./app2
    container_name: app2
    ports:
      - "5005:5005"
    depends_on:
      - redis
    networks:
      - app-network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
