version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  app1:
    image: microservicecicdtest_app1:latest  # Explicitly tag the image
    build:
      context: ./app1
    container_name: app1
    ports:
      - "5004:5004"
    depends_on:
      - redis
    networks:
      - app-network

  app2:
    image: microservicecicdtest_app2:latest  # Explicitly tag the image
    build:
      context: ./app2
    container_name: app2
    ports:
      - "5005:5005"
    depends_on:
      - redis
    networks:
      - app-network
