version: '3.8'

networks:
  app-network:
    driver: bridge
    external: true

services:
  redis:
    image: redis:6.2
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

  app:
    image: "${APP_IMAGE:-rohittru/microservicecicdtest_default:latest}"
    container_name: "${APP_NAME:-default-app}"
    restart: always
    ports:
      - "${APP_PORT:-5004}:${APP_PORT:-5004}"
    environment:
      - SERVICE_NAME=${APP_NAME:-default-app}
      - APP_PORT=${APP_PORT:-5004}
      - VIRTUAL_HOST=${APP_NAME}.emerginary.com   
      - VIRTUAL_PORT=${APP_PORT:-5004}            
    depends_on:
      - redis
    networks:
      - app-network

  nginx:
    image: jwilder/nginx-proxy:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro  
      - ./nginx/conf.d:/etc/nginx/conf.d:ro        
    environment:
      - DEFAULT_HOST=default.emerginary.com        
    networks:
      - app-network                                
