version: '3.8'

networks:
  app-network:
    external: true

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - app-network
    environment:
      - DEFAULT_HOST=stockbotwars.emerginary.com
